# Custom Configuration for GenAI IDP Testing
# SPDX-License-Identifier: MIT-0

notes: Custom test configuration for deployment validation

ocr:
  backend: "textract"
  model_id: "us.anthropic.claude-3-7-sonnet-20250219-v1:0"
  system_prompt: "You are an expert OCR system. Extract all text from the provided image accurately."
  task_prompt: "Extract all text from this document image. Preserve the layout and formatting."
  features:
    - name: LAYOUT
    - name: TABLES
    - name: SIGNATURES

classes:
  - name: Invoice
    description: >-
      A commercial document that itemizes and records a transaction between a buyer and seller.
      Contains details about products/services, quantities, prices, and payment terms.
    attributes:
      - name: InvoiceNumber
        description: >-
          Unique identifier assigned to the invoice for tracking and reference purposes.
        evaluation_method: EXACT
        attributeType: simple
      - name: InvoiceDate
        description: >-
          The date when the invoice was issued or created.
        evaluation_method: EXACT
        attributeType: simple
      - name: TotalAmount
        description: >-
          The total amount due including all items, taxes, and fees.
        evaluation_method: NUMERIC_EXACT
        attributeType: simple
      - name: VendorName
        description: >-
          The name of the company or individual issuing the invoice.
        evaluation_method: EXACT
        attributeType: simple

  - name: Receipt
    description: >-
      A document acknowledging that a person has received money or property in payment.
      Shows proof of purchase with transaction details.
    attributes:
      - name: TransactionDate
        description: >-
          The date when the transaction occurred.
        evaluation_method: EXACT
        attributeType: simple
      - name: Amount
        description: >-
          The total amount paid for the transaction.
        evaluation_method: NUMERIC_EXACT
        attributeType: simple
      - name: MerchantName
        description: >-
          The name of the business or merchant where the transaction took place.
        evaluation_method: EXACT
        attributeType: simple

classification:
  model_id: "us.anthropic.claude-3-7-sonnet-20250219-v1:0"
  system_prompt: "You are an expert document classifier."
  task_prompt: "Classify this document into one of the provided categories based on its content and structure."

extraction:
  model_id: "us.anthropic.claude-3-7-sonnet-20250219-v1:0"
  system_prompt: "You are an expert at extracting structured information from documents."
  task_prompt: "Extract the requested information from this document and return it in JSON format."
