# SPDX-License-Identifier: MIT-0

ocr:
  backend: "textract"
  model_id: "us.anthropic.claude-3-7-sonnet-20250219-v1:0"
  features:
    - name: LAYOUT
    - name: TABLES
    - name: SIGNATURES

classes:
  - name: Invoice
    description: Commercial document with itemized transaction details between buyer and seller
    attributes:
      - name: InvoiceNumber
        description: Unique invoice identifier
        evaluation_method: EXACT
        attributeType: simple
      - name: InvoiceDate
        description: Invoice issue date
        evaluation_method: EXACT
        attributeType: simple
      - name: TotalAmount
        description: Total amount due
        evaluation_method: NUMERIC_EXACT
        attributeType: simple
      - name: VendorName
        description: Invoice issuer name
        evaluation_method: EXACT
        attributeType: simple

  - name: Receipt
    description: Payment acknowledgment document with transaction details
    attributes:
      - name: TransactionDate
        description: Transaction date
        evaluation_method: EXACT
        attributeType: simple
      - name: Amount
        description: Transaction amount
        evaluation_method: NUMERIC_EXACT
        attributeType: simple
      - name: MerchantName
        description: Business name
        evaluation_method: EXACT
        attributeType: simple

classification:
  model_id: "us.anthropic.claude-3-7-sonnet-20250219-v1:0"

extraction:
  model_id: "us.anthropic.claude-3-7-sonnet-20250219-v1:0"
