# Summarization Service Configuration
summarization:
  top_p: "0.1"
  max_tokens: "4096"
  top_k: "5"
  temperature: "0.0"
  model: "us.amazon.nova-pro-v1:0"
  system_prompt: "You are a document summarization expert. Your task is to create comprehensive, accurate summaries of document content while preserving key information and maintaining factual accuracy."
  # Configuration for different summarization approaches
  section_based_summarization: true
  whole_document_fallback: true
  output_formats:
    - "json"
    - "markdown"
  # Additional summarization-specific settings can be added here
