# Document Classes and Attributes Configuration
classes:
  - name: "letter"
    description: "A formal written correspondence with sender/recipient addresses, date, salutation, body, and closing signature"
    attributes:
      - name: "sender_name"
        description: "The name of the person or entity who wrote or sent the letter. Look for text following or near terms like 'from', 'sender', 'authored by', 'written by', or at the end of the letter before a signature."
        confidence_threshold: "0.85"
      - name: "sender_address"
        description: "The physical address of the sender, typically appearing at the top of the letter. May be labeled as 'address', 'location', or 'from address'."
        confidence_threshold: "0.8"
      - name: "recipient_name"
        description: "The name of the person or entity receiving the letter. Look for this after 'to', 'recipient', 'addressee', or at the beginning of the letter."
        confidence_threshold: "0.9"
      - name: "recipient_address"
        description: "The physical address where the letter is to be delivered. Often labeled as 'to address' or 'delivery address', typically appearing below the recipient name."
      - name: "date"
        description: "The date when the letter was written. Look for a standalone date or text following phrases like 'written on' or 'dated'."
      - name: "subject"
        description: "The topic or main point of the letter. Often preceded by 'subject', 'RE:', or 'regarding'."
      - name: "letter_type"
        description: "The category or classification of the letter, such as 'complaint', 'inquiry', 'invitation', etc. May be indicated by 'type' or 'category'."
      - name: "signature"
        description: "The handwritten name or mark of the sender at the end of the letter. May follow terms like 'signed by' or simply appear at the bottom of the document."
      - name: "cc"
        description: "Names of people who receive a copy of the letter in addition to the main recipient. Often preceded by 'cc', 'carbon copy', or 'copy to'."
      - name: "reference_number"
        description: "An identifying number or code associated with the letter. Look for labels like 'ref', 'reference', or 'our ref'."

  - name: "form"
    description: "A structured document with labeled fields, checkboxes, or blanks requiring user input and completion"
    attributes:
      - name: "form_type"
        description: "The category or purpose of the form, such as 'application', 'registration', 'request', etc. May be identified by 'form name', 'document type', or 'form category'."
      - name: "form_id"
        description: "The unique identifier for the form, typically a number or alphanumeric code. Often labeled as 'form number', 'id', or 'reference number'."
      - name: "submission_date"
        description: "The date when the form was submitted or filed. Look for text near 'date', 'submitted on', or 'filed on'."
      - name: "submitter_name"
        description: "The name of the person who submitted the form. May be labeled as 'name', 'submitted by', or 'filed by'."
      - name: "submitter_id"
        description: "An identification number for the person submitting the form, such as social security number, employee ID, etc. Often labeled as 'id number', 'identification', or 'reference'."
      - name: "approval_status"
        description: "The current state of approval for the form, such as 'approved', 'pending', 'rejected', etc. Look for terms like 'status', 'approved', or 'pending'."
      - name: "processed_by"
        description: "The name of the person or department that processed the form. May be indicated by 'processor', 'handled by', or 'approved by'."
      - name: "processing_date"
        description: "The date when the form was processed or completed. Look for labels like 'processed on' or 'completion date'."
      - name: "department"
        description: "The organizational unit responsible for the form. Often abbreviated as 'dept' or may appear as 'department' or 'division'."
      - name: "comments"
        description: "Additional notes or remarks about the form. Look for sections labeled 'notes', 'remarks', or 'comments'."

  - name: "email"
    description: "A digital message with email headers (To/From/Subject), timestamps, and conversational threading"
    attributes:
      - name: "from_address"
        description: "The email address of the sender. Look for text following 'from', 'sender', or 'sent by', typically at the beginning of the email header."
      - name: "to_address"
        description: "The email address of the primary recipient. May be labeled as 'to', 'recipient', or 'sent to'."
      - name: "cc_address"
        description: "Email addresses of additional recipients who receive copies. Look for 'cc' or 'carbon copy' followed by one or more email addresses."
      - name: "bcc_address"
        description: "Email addresses of hidden recipients. May be labeled as 'bcc' or 'blind copy'."
      - name: "subject"
        description: "The topic of the email. Often preceded by 'subject', 'RE:', or 'regarding'."
      - name: "date_sent"
        description: "The date and time when the email was sent. Look for 'date', 'sent on', or 'received', typically in the email header."
      - name: "attachments"
        description: "Files included with the email. May be indicated by 'attached', 'attachment', or 'enclosed', often with icons or file names."
      - name: "priority"
        description: "The urgency level of the email, such as 'high', 'normal', etc. Look for 'priority' or 'importance'."
      - name: "thread_id"
        description: "An identifier for the email conversation. May be labeled as 'thread' or 'conversation', typically not visible to regular users."
      - name: "message_id"
        description: "A unique identifier for the specific email. Look for 'message id' or 'email id', usually hidden in the email metadata."
